# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'first1.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

# import Oracle
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(182, 322)
        font = QtGui.QFont()
        font.setPointSize(12)
        Dialog.setFont(font)
        Dialog.setStyleSheet("QPushButton {\n"
"    font-size: 20px;\n"
"    font-weight: bold;\n"
"    border: none;    \n"
"    background-color: white;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: silver;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: red;\n"
"} \n"
"\n"
"QLabel {\n"
"    text-align: center;\n"
"}")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(10, 40, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Azonix")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 110, 171, 21))
        font = QtGui.QFont()
        font.setFamily("Sansita Swashed Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 160, 171, 21))
        font = QtGui.QFont()
        font.setFamily("Sansita Swashed Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(10, 210, 171, 21))
        font = QtGui.QFont()
        font.setFamily("Sansita Swashed Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(10, 260, 171, 21))
        font = QtGui.QFont()
        font.setFamily("Sansita Swashed Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.lprint_1 = QtWidgets.QLabel(Dialog)
        self.lprint_1.setGeometry(QtCore.QRect(10, 130, 171, 31))
        self.lprint_1.setText("")
        self.lprint_1.setAlignment(QtCore.Qt.AlignCenter)
        self.lprint_1.setObjectName("lprint_1")
        self.lprint_2 = QtWidgets.QLabel(Dialog)
        self.lprint_2.setGeometry(QtCore.QRect(10, 180, 171, 31))
        self.lprint_2.setText("")
        self.lprint_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lprint_2.setObjectName("lprint_2")
        self.lprint_3 = QtWidgets.QLabel(Dialog)
        self.lprint_3.setGeometry(QtCore.QRect(10, 230, 171, 31))
        self.lprint_3.setText("")
        self.lprint_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lprint_3.setObjectName("lprint_3")
        self.lprint_4 = QtWidgets.QLabel(Dialog)
        self.lprint_4.setGeometry(QtCore.QRect(10, 280, 171, 31))
        self.lprint_4.setText("")
        self.lprint_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lprint_4.setObjectName("lprint_4")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(10, 10, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setFrame(True)
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_2.setGeometry(QtCore.QRect(50, 10, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_3.setGeometry(QtCore.QRect(90, 10, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_3.setObjectName("lineEdit_3")

        

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", "Discover"))
        self.label.setText(_translate("Dialog", "Кол-во дней до сегодня"))
        self.label_2.setText(_translate("Dialog", "Високосность"))
        self.label_3.setText(_translate("Dialog", "Знак  зодиака"))
        self.label_4.setText(_translate("Dialog", "Название "))
        self.lineEdit.setText(_translate("Dialog", "дд"))
        self.lineEdit_2.setText(_translate("Dialog", "мм"))
        self.lineEdit_3.setText(_translate("Dialog", "гггг"))


